[project]
name = "pm2-5-to-aqi-index-formula"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
]
